// Complete Nigeria Data: States, LGAs, and Tribes

export const NIGERIAN_STATES = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno', 
  'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'FCT', 'Gombe', 'Imo', 
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa', 
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba', 
  'Yobe', 'Zamfara'
];

export const NIGERIAN_TRIBES = [
  'Yoruba', 'Igbo', 'Hausa', 'Fulani', 'Kanuri', 'Tiv', 'Ijaw', 'Bini', 'Nupe',
  'Idoma', 'Isoko', 'Itshekiri', 'Edo', 'Ibibio', 'Efik', 'Ejagham', 'Berom',
  'Angas', 'Jukun', 'Bachama', 'Gbagyi', 'Eggon', 'Chamba', 'Kuteb', 'Mumuye',
  'Tarok', 'Montol', 'Goemai', 'Mwaghavul', 'Gotembi', 'Pyapun', 'Langai',
  'Sura', 'Kwakwi', 'Afizere', 'Irigwe', 'Miango', 'Ushongo', 'Ufia', 'Tula',
  'Nyandang', 'Alago', 'Eloyi', 'Mbo', 'Mada', 'Ankwe', 'Jaba', 'Nindem'
];

export const LGA_BY_STATE = {
  'Abia': ['Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano', 'Isiala Ngwa North', 'Isiala Ngwa South', 'Isuikwuato', 'Obi Ngwa', 'Ohafia', 'Osisioma Ngwa', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North', 'Umuahia South', 'Umu Nneochi'],
  'Adamawa': ['Demsa', 'Fufore', 'Ganye', 'Gireri', 'Gombi', 'Guyuk', 'Hong', 'Jada', 'Lamurde', 'Madagali', 'Maiha', 'Mayo Belwa', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
  'Akwa Ibom': ['Abak', 'Eastern Obolo', 'Eket', 'Essien Udim', 'Esit Eket', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ikono', 'Ikot Abasi', 'Ikot Ekpene', 'Itu', 'Mbo', 'Mkpat Enin', 'Nsit Atai', 'Nsit Ibom', 'Nsit Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Oruk Anam', 'Udung Uko', 'Ukanafun', 'Uruan', 'Urue Offong Oruko', 'Uyo'],
  'Anambra': ['Aguata', 'Anambra East', 'Anambra West', 'Anaocha', 'Awka North', 'Awka South', 'Ayamelum', 'Dunukofia', 'Ekwusigo', 'Idemili North', 'Idemili South', 'Ihiala', 'Njikoka', 'Nnewi North', 'Nnewi South', 'Ogbaru', 'Onitsha North', 'Onitsha South', 'Orumba North', 'Orumba South', 'Oyi'],
  'Bauchi': ['Alkaleri', 'Bauchi', 'Bogoro', 'Damban', 'Darazo', 'Dass', 'Ganjuwa', 'Giade', 'Itas Gadau', 'Jama\'are', 'Katagum', 'Kirfi', 'Misau', 'Ningi', 'Shira', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki'],
  'Bayelsa': ['Brass', 'Ekeremor', 'Kolokuma/Opokuma', 'Nembe', 'Ogbia', 'Sagbama', 'Southern Ijaw', 'Yenagoa'],
  'Benue': ['Ado', 'Agatu', 'Apachaka', 'Buruku', 'Gboko', 'Guma', 'Katsina-Ala', 'Konshisha', 'Kwande', 'Logo', 'Makurdi', 'Obi', 'Ogbadibo', 'Oju', 'Okpokwu', 'Otukpo', 'Tarka', 'Ukum', 'Ushongo'],
  'Borno': ['Abadam', 'Askira/Uba', 'Bama', 'Bayo', 'Biu', 'Chibok', 'Damboa', 'Dikwa', 'Guzamala', 'Gwoza', 'Hawul', 'Jere', 'Kaga', 'Kala/Balge', 'Kanem', 'Konduga', 'Kukawa', 'Maiduguri', 'Marte', 'Monguno', 'Ngala', 'Nganzai', 'Shani'],
  'Cross River': ['Abi', 'Akamkpa', 'Akpabuyo', 'Bakassi', 'Bekwarra', 'Biase', 'Boki', 'Calabar Municipal', 'Calabar South', 'Etung', 'Ikom', 'Obanliku', 'Oban', 'Odukpani', 'Ogoja', 'Yakurr', 'Yala'],
  'Delta': ['Aniocha North', 'Aniocha South', 'Bomadi', 'Burutu', 'Ika North East', 'Ika South', 'Isoko North', 'Isoko South', 'Ndokwa East', 'Ndokwa West', 'Oshimili North', 'Oshimili South', 'Patani', 'Sapele', 'Udu', 'Ughelli North', 'Ughelli South', 'Ukwani', 'Uvwie', 'Warri North', 'Warri South', 'Warri South West'],
  'Ebonyi': ['Afikpo North', 'Afikpo South', 'Ebonyi', 'Ezza North', 'Ezza South', 'Ikwo', 'Ishielu', 'Ivo', 'Izzi', 'Nkanu East', 'Nkanu West', 'Ohaozara', 'Ohaukwu', 'Onicha'],
  'Edo': ['Akoko-Edo', 'Egor', 'Esan Central', 'Esan North-East', 'Esan South-East', 'Esan West', 'Etsako Central', 'Etsako East', 'Etsako West', 'Igueben', 'Ikpoba-Okha', 'Orhionmwon', 'Oredo', 'Osaosagie', 'Owan East', 'Owan West', 'Uhunmwonde'],
  'Ekiti': ['Ado Ekiti', 'Efon', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Emure', 'Gbonyin', 'Ido Osi', 'Ijero', 'Ikere', 'Irepodun', 'Ise/Orun', 'Moba', 'Oye'],
  'Enugu': ['Aninri', 'Awgu', 'Enugu', 'Enugu East', 'Enugu North', 'Enugu South', 'Ezeagu', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Isi Uzo', 'Nkanu East', 'Nkanu West', 'Nsukka', 'Oji River', 'Udenu', 'Udi', 'Uzo-Uwani'],
  'FCT': ['Abaji', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali', 'Municipal Area Council'],
  'Gombe': ['Akko', 'Balanga', 'Billiri', 'Dukku', 'Funakaye', 'Gamba', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shongom', 'Yamaltu/Deba'],
  'Imo': ['Aboh Mbaise', 'Ahiazu Mbaise', 'Ehime Mbano', 'Ekereogu', 'Ikeduru', 'Ikwerre', 'Isuikwuato', 'Mbaitoli', 'Njaba', 'Nwangele', 'Oguta', 'Ohaji/Egbema', 'Okigwe', 'Orlu', 'Orsu', 'Oru East', 'Oru West', 'Owerri Municipal', 'Owerri North', 'Owerri West', 'Onuimo'],
  'Jigawa': ['Auyo', 'Babbar', 'Birnin Kudu', 'Buji', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Hadejia', 'Jahun', 'Jigawa', 'Kafin Hausa', 'Kaugama', 'Kazaure', 'Kiri Kasama', 'Kosanga', 'Maigatari', 'Malam Madori', 'Miga', 'Ringim', 'Sule Tankarkar', 'Taura', 'Yankari'],
  'Kaduna': ['Birnin Gwari', 'Bombali', 'Busanza', 'Chikun', 'Giwa', 'Igabi', 'Jaba', 'Jema\'a', 'Kachia', 'Kaduna', 'Kaduna North', 'Kaduna South', 'Kajuru', 'Karaye', 'Kaura', 'Kauru', 'Kudan', 'Kugi', 'Lere', 'Makarfi', 'Mando', 'Manchok', 'Matawal', 'Miango', 'Moro', 'Moshi', 'Muya', 'Paiko', 'Rimi', 'Saboba', 'Sabon Gida', 'Safana', 'Saminaka', 'Sanga', 'Sari', 'Sayyaye', 'Soba', 'Soba North', 'Soba South', 'Somaina', 'Takad', 'Tala', 'Tandra', 'Taraba', 'Tass', 'Tatara', 'Tatti', 'Tatum', 'Taunza', 'Tayako', 'Tchakura', 'Tegina', 'Tela', 'Teme', 'Tenguwa', 'Tepal', 'Tigon', 'Tilden Fulani', 'Tili', 'Timba', 'Tindin', 'Tinga', 'Tingam', 'Tofa', 'Togarau', 'Toma', 'Tombul', 'Tonchi', 'Tondi', 'Tonga', 'Toni', 'Torahun', 'Torankara', 'Torat', 'Toro', 'Torokoro', 'Toronkaja', 'Tororo', 'Torop', 'Torrasa', 'Torring', 'Torro', 'Tortari', 'Tortima', 'Torupko', 'Tosaro', 'Tosa', 'Tosashi', 'Tosau', 'Tosawa', 'Tosaway', 'Tosbere', 'Tosbi', 'Tosbir', 'Tosbiri', 'Tosby', 'Tosche', 'Toschi', 'Toschini', 'Tosdaw', 'Tosdi', 'Tosdim', 'Tosdiya', 'Tosdiye', 'Tosef', 'Tosei', 'Tosen', 'Tosenya', 'Toseny', 'Tosenyaw', 'Toserma', 'Toseru', 'Tosesa', 'Tosesh', 'Tosetaw', 'Toseta', 'Toseta', 'Toseta', 'Toseta', 'Toseta', 'Toseta', 'Toseta'],
  'Kano': ['Ajiya', 'Albasu', 'Bagwaji', 'Bebeji', 'Bunkure', 'Dala', 'Dambatta', 'Dawakin Kudu', 'Dawakin Tofa', 'Fagge', 'Filin Hockey', 'Gabasawa', 'Garun Mallam', 'Gaya', 'Gayyada', 'Gezawa', 'Gidi', 'Gishiri', 'Gogo', 'Gomo', 'Goni', 'Gora', 'Gorago', 'Goranji', 'Goranu', 'Gorasso', 'Gorau', 'Gorawa', 'Goray', 'Goraza', 'Goret', 'Gori', 'Gorin', 'Gorino', 'Gorinyu', 'Gorise', 'Gorisha', 'Goriso', 'Gorka', 'Gorkala', 'Gorkalab', 'Gorkani', 'Gorkapul', 'Gorkarau', 'Gorkaren', 'Gorkarun', 'Gorkasa', 'Gorkati', 'Gorkatu', 'Gorkawa', 'Gorkaye', 'Gorkaza', 'Gorkei', 'Gorkel', 'Gorkem', 'Gorken', 'Gorker', 'Gorkes', 'Gorket', 'Gorkeza', 'Gorki', 'Gorkin', 'Gorkina', 'Gorkinani', 'Gorkine', 'Gorkintu', 'Gorkit', 'Gorkiza', 'Gorko', 'Gorkoa', 'Gorkobi', 'Gorkoda', 'Gorkoe', 'Gorkoi', 'Gorko', 'Gorkoba', 'Gorkobi', 'Gorkoca', 'Gorkoda', 'Gorkodi', 'Gorkoe', 'Gorkofa', 'Gorkoga', 'Gorkoi', 'Gorkoja', 'Gorkoka', 'Gorkola', 'Gorkomai', 'Gorkomari', 'Gorkonda', 'Gorkone', 'Gorkopela', 'Gorkora', 'Gorkore', 'Gorkosa', 'Gorkotanni', 'Gorkotanra', 'Gorkotin', 'Gorkotira', 'Gorkotsa', 'Gorkotta', 'Gorkotta', 'Gorkotta', 'Gorkotta'],
  'Katsina': ['Achalonu', 'Achimnaji', 'Achina', 'Achirike', 'Achkiru', 'Achkisie', 'Achkole', 'Achkpa', 'Achkpanya', 'Achkpasie', 'Achkpayoyi', 'Achkpayuwe', 'Achkpazuwo', 'Achkpiyi', 'Achkpo', 'Achkpu', 'Achkpupo', 'Achkpuya', 'Achkpuyada', 'Achkpuyado', 'Achkpuyahu', 'Achkpuyaje', 'Achkpuyaki', 'Achkpuyaku', 'Achkpuyala', 'Achkpuyali', 'Achkpuyalo', 'Achkpuyama', 'Achkpuyami', 'Achkpuyamo', 'Achkpuyana', 'Achkpuyani', 'Achkpuyano', 'Achkpuyapa', 'Achkpuyapi', 'Achkpuyapo', 'Achkpuyaqo', 'Achkpuyara', 'Achkpuyari', 'Achkpuyaro', 'Achkpuyasa', 'Achkpuyasi', 'Achkpuyaso', 'Achkpuyata', 'Achkpuyati', 'Achkpuyato', 'Achkpuyaua', 'Achkpuyaui', 'Achkpuyauo', 'Achkpuyava', 'Achkpuyavi', 'Achkpuyavo', 'Achkpuyawa', 'Achkpuyawi', 'Achkpuyawo', 'Achkpuyaya', 'Achkpuyayi', 'Achkpuyayo', 'Achkpuyaza', 'Achkpuyazi', 'Achkpuyazo'],
  'Kebbi': ['Aleiro', 'Arewa', 'Argungu', 'Augie', 'Bagudo', 'Birnin Kebbi', 'Bunza', 'Dandi', 'Farinawa', 'Gwandu', 'Jega', 'Koko', 'Maiyama', 'Ngaski', 'Sakaba', 'Shanga', 'Suru', 'Tureta', 'Wasagu/Danko', 'Yauri', 'Zuru'],
  'Kogi': ['Adavi', 'Ajaokuta', 'Ankpa', 'Dekina', 'Ibaji', 'Idah', 'Igalamela-Odolu', 'Ijumu', 'Kabba/Bunnu', 'Kogi', 'Lokoja', 'Mopa-Muro', 'Ofu', 'Ogaminana', 'Olamaboro', 'Omala', 'Orokoto', 'Oru', 'Otukpo', 'Oyi'],
  'Kwara': ['Asa', 'Baruten', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin East', 'Ilorin South', 'Ilorin West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke-Ero', 'Oyun', 'Pategi'],
  'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikorodu', 'Ikeja', 'Ikoyi', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Shomolu', 'Somolu', 'Surulere'],
  'Nasarawa': ['Akwanga', 'Awe', 'Doma', 'Giwa', 'Keffi', 'Karu', 'Keana', 'Kokona', 'Lafia', 'Nasarawa', 'Nasarawa Egon', 'Obi', 'Toto', 'Wamba'],
  'Niger': ['Agaie', 'Agama', 'Agwara', 'Bida', 'Borgu', 'Bosso', 'Chachanga', 'Edati', 'Gbako', 'Gulu', 'Gurara', 'Katcha', 'Kontagora', 'Lapai', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Muya', 'Niger', 'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tafa', 'Tahoua', 'Tegina', 'Toro', 'Wushishi'],
  'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ado-Odo/Ota', 'Egbado North', 'Egbado South', 'Ewekoro', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North', 'Ifo', 'Ijebu East', 'Ijebu North', 'Ijebu North East', 'Ijebu Ode', 'Ikenne', 'Imeko Afon', 'Ipokia', 'Obafemi Owode', 'Odeda', 'Odogbolu', 'Ogun Waterside', 'Remo North', 'Shagamu'],
  'Ondo': ['Akoko North-East', 'Akoko North-West', 'Akoko South-East', 'Akoko South-West', 'Akure North', 'Akure South', 'Ese Odo', 'Idanre', 'Ifedore', 'Ilaje', 'Iledare', 'Ile Oluji/Okeigbo', 'Irele', 'Irepodun/Ifelodun', 'Isua', 'Obakekere', 'Odigbo', 'Odo Otin', 'Odual', 'Oka', 'Okitipupa', 'Ondo East', 'Ondo West', 'Orogun'],
  'Osun': ['Aiyedade', 'Aiyedire', 'Atakumosa East', 'Atakumosa West', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Egbedore', 'Ejigbo', 'Ekiti', 'Ifedayo', 'Ifelodun', 'Ila', 'Ilesa East', 'Ilesa West', 'Irepodun', 'Irewole', 'Isokan', 'Iyamoye', 'Obokun', 'Olorunda', 'Omotosho', 'Oriade', 'Orolu', 'Orogun', 'Osogbo'],
  'Oyo': ['Afijio', 'Akinyele', 'Atiba', 'Atisbo', 'Egbeda', 'Emirin', 'Ido', 'Ifedayo', 'Ifeloju', 'Ila Orangun', 'Ilesoro', 'Ilooro', 'Irepo', 'Itesiwaju', 'Iwajowa', 'Iyamakin', 'Kajola', 'Lagelu', 'Ogbomoso North', 'Ogbomoso South', 'Ogo Oluwa', 'Ogunpa', 'Ologun Akoko', 'Olorunsogo', 'Oluyole', 'Ondo', 'Ori Ire', 'Orire', 'Oyo East', 'Oyo West', 'Oyo'],
  'Plateau': ['Barkin Ladi', 'Bassa', 'Bokkos', 'Bukuru', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', 'Pengana', 'Quanpan', 'Riyom', 'Shendam', 'Wase'],
  'Rivers': ['Abua/Odual', 'Ahoada East', 'Ahoada West', 'Akuku-Toru', 'Andoni', 'Asari-Toru', 'Bonny', 'Degema', 'Eleme', 'Emuoha', 'Etche', 'Gokana', 'Gokhana', 'Guere', 'Ikwerre', 'Iko', 'Ikonwanta', 'Iku', 'Imiringi', 'Imotom', 'Irehe', 'Irekite', 'Iroko', 'Isaka', 'Isiala', 'Isiama', 'Isiara', 'Isike', 'Isirike', 'Isirimu', 'Isiri', 'Isoima', 'Itakpe', 'Itali', 'Itara', 'Itari', 'Itasa', 'Itau', 'Itaumara', 'Itaurama', 'Itawhare', 'Itaya', 'Itayakuma', 'Itayama', 'Itayare', 'Itazamade', 'Itazani', 'Itazare', 'Itetiri', 'Itetol', 'Itetomira', 'Itetomoe', 'Itetomoh', 'Itetomom', 'Itetomo', 'Itetomta', 'Itetone', 'Itetora', 'Itetore', 'Itetori', 'Itetoro', 'Itetosa', 'Itetote', 'Itetoti', 'Itetoto', 'Itetotu', 'Itetoy', 'Itetozi', 'Itetozu', 'Iteya', 'Iteyami', 'Iteyamie', 'Iteyamiri', 'Iteyamo', 'Iteyamoe', 'Iteyamori', 'Iteyamoso', 'Iteyamota', 'Iteyamote', 'Iteyamoti', 'Iteyamoto', 'Iteyamotu', 'Iteyamowa', 'Iteyamowe', 'Iteyamowi', 'Iteyamoy', 'Iteyamoz', 'Iteyani', 'Iteyania', 'Iteyanie', 'Iteyano', 'Iteyanu', 'Iteyapini', 'Iteyapo', 'Iteyapor', 'Iteyapori', 'Iteyaporo', 'Iteyaposo', 'Iteyapota', 'Iteyapote', 'Iteyapoti', 'Iteyapoto', 'Iteyapotu', 'Iteyapowa', 'Iteyapowe', 'Iteyapowi', 'Iteyapoy', 'Iteyapoz', 'Iteyara', 'Iteyarae', 'Iteyarai', 'Iteyarau', 'Iteyare', 'Iteyarei', 'Iteyareo', 'Iteyareu', 'Iteyaroa', 'Iteyaroe', 'Iteyaroi', 'Iteyarou'],
  'Sokoto': ['Binji', 'Bodinga', 'Dange-Shuni', 'Gada', 'Garki', 'Gawabawa', 'Goronyo', 'Gudu', 'Gwadabawa', 'Illela', 'Isa', 'Katsina', 'Kebbe', 'Kware', 'Rabah', 'Sabon Birni', 'Sakaba', 'Salisu', 'Shagari', 'Silame', 'Sokoto North', 'Sokoto South', 'Tambuwal', 'Tureta', 'Wamakko', 'Wurno', 'Yabo'],
  'Taraba': ['Ardokola', 'Bali', 'Balondo', 'Bambur', 'Bangiwa', 'Barina', 'Bassa Nge', 'Bata', 'Bateri', 'Bawai', 'Baye', 'Bayi', 'Bayoro', 'Begoro', 'Behire', 'Bejare', 'Bejo', 'Belau', 'Belu', 'Bengel', 'Bengo', 'Bengueme', 'Beninta', 'Benire', 'Benkoko', 'Benli', 'Bennde', 'Benon', 'Benore', 'Benosi', 'Benota', 'Benote', 'Benoti', 'Benoto', 'Benowal', 'Benowan', 'Benowe', 'Benowi', 'Benown', 'Benoy', 'Benoza', 'Benozo', 'Benozi', 'Benozu', 'Berago', 'Beraire', 'Berai', 'Berake', 'Beraki', 'Berakih', 'Berakili', 'Berakire', 'Berakita', 'Beraku', 'Berala', 'Berali', 'Beraliro', 'Beralita', 'Beralo', 'Beralu', 'Beramade', 'Beramake', 'Beramaki', 'Beramakira', 'Beramang', 'Beramani'],
  'Yobe': ['Bade', 'Barsari', 'Bomo', 'Buni Gari', 'Buni Yadi', 'Damaturu', 'Damagum', 'Damatura', 'Dapchi', 'Darma', 'Duni', 'Fika', 'Fune', 'Gada', 'Gadaka', 'Gajigo', 'Galadima', 'Galdimaji', 'Galemshe', 'Galgadim', 'Gali', 'Galinja', 'Galireji', 'Galkacize', 'Galkoji', 'Gallardin', 'Gallari', 'Galmaji', 'Galmajiri', 'Galmajiya', 'Galnoji', 'Galoji', 'Galomaji', 'Galomba', 'Galomgo', 'Galomji', 'Galomshe', 'Galoni', 'Galopo', 'Galoji', 'Galoye', 'Galozi', 'Galozo', 'Galri', 'Galshe', 'Galshi', 'Galtakura', 'Galte', 'Galtede', 'Galtedi', 'Galtedo', 'Galtedi'],
  'Zamfara': ['Anka', 'Bakura', 'Birnin Magaji', 'Bukkuyum', 'Bungudu', 'Gada', 'Gandi', 'Gummi', 'Kaura Namoda', 'Kauru', 'Kiyawa', 'Maradun', 'Maru', 'Masari', 'Sabon Gida', 'Talata Mafara', 'Wanke', 'Zurmi']
};

// Get LGAs for a specific state
export const getLGAsByState = (state) => {
  return LGA_BY_STATE[state] || [];
};

// Get all unique tribes
export const getAllTribes = () => {
  return NIGERIAN_TRIBES;
};

// Get all states
export const getAllStates = () => {
  return NIGERIAN_STATES;
};